/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shy_udpclient_HelloUtils */

#ifndef _Included_com_shy_udpclient_HelloUtils
#define _Included_com_shy_udpclient_HelloUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shy_udpclient_HelloUtils
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shy_udpclient_HelloUtils_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
